{
 "title": "Custom-Queries",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "esxtop" },
   {
    "name": "Host",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurements(bucket: \"esxtop\")\n|> yield()"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "from(bucket: \"esxtop\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Physical Cpu\")\n  |> group(columns: [\"instance\"])\n  |> distinct(column: \"instance\")\n  |> yield()"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PCPU %Core Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Physical Cpu\")\n  |> filter(fn: (r) => r.instance =~ /^${Instance:regex}$/)\n  |> filter(fn: (r) => r._field == \"% Core Util Time\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: 50ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PCPU>=100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Physical Cpu\")\n//  |> filter(fn: (r) => r.instance =~ /${Instance:regex}/)\n  |> filter(fn: (r) => r._field == \"% Core Util Time\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: 50ms, fn: mean, createEmpty: false)\n  |> filter(fn: (r) => r._value == 100.0)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PCPU-vCPU Mapping",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r._field == \"Physical Cpu\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> filter(fn: (r) => string(v: int(v: r._value)) =~ /^${Instance:regex}$/)   // ✅ here\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Vcpu-%Run",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "instSet =\n  from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n    |> filter(fn: (r) => r.group == \"Vcpu\")\n    |> filter(fn: (r) => r._field == \"Physical Cpu\")\n    |> group(columns: [\"_measurement\", \"instance\"]) // your logic\n    |> filter(fn: (r) => string(v: int(v: r._value)) =~ /^${Instance:regex}$/)\n    |> keep(columns: [\"instance\"])\n    |> distinct(column: \"instance\")\n    |> group() // ✅ merge all instance tables into one\n    |> findColumn(fn: (key) => true, column: \"instance\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r._field == \"% Run\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> filter(fn: (r) => contains(value: r.instance, set: instSet))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "vCPU-%Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "instSet =\n  from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n    |> filter(fn: (r) => r.group == \"Vcpu\")\n    |> filter(fn: (r) => r._field == \"Physical Cpu\")\n    |> group(columns: [\"_measurement\", \"instance\"]) // your logic\n    |> filter(fn: (r) => string(v: int(v: r._value)) =~ /^${Instance:regex}$/)\n    |> keep(columns: [\"instance\"])\n    |> distinct(column: \"instance\")\n    |> group() // ✅ merge all instance tables into one\n    |> findColumn(fn: (key) => true, column: \"instance\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r._field == \"% Used\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> filter(fn: (r) => contains(value: r.instance, set: instSet))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Vcpu-%CoStop",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "instSet =\n  from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n    |> filter(fn: (r) => r.group == \"Vcpu\")\n    |> filter(fn: (r) => r._field == \"Physical Cpu\")\n    |> group(columns: [\"_measurement\", \"instance\"]) // your logic\n    |> filter(fn: (r) => string(v: int(v: r._value)) =~ /^${Instance:regex}$/)\n    |> keep(columns: [\"instance\"])\n    |> distinct(column: \"instance\")\n    |> group() // ✅ merge all instance tables into one\n    |> findColumn(fn: (key) => true, column: \"instance\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r._field == \"% CoStop\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> filter(fn: (r) => contains(value: r.instance, set: instSet))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Vcpu-%RDY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "query": "instSet =\n  from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n    |> filter(fn: (r) => r.group == \"Vcpu\")\n    |> filter(fn: (r) => r._field == \"Physical Cpu\")\n    |> group(columns: [\"_measurement\", \"instance\"]) // your logic\n    |> filter(fn: (r) => string(v: int(v: r._value)) =~ /^${Instance:regex}$/)\n    |> keep(columns: [\"instance\"])\n    |> distinct(column: \"instance\")\n    |> group() // ✅ merge all instance tables into one\n    |> findColumn(fn: (key) => true, column: \"instance\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r._field == \"% Ready\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> filter(fn: (r) => contains(value: r.instance, set: instSet))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "NetWorld-% Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /:NetWorld-VM-/)\n  |> filter(fn: (r) => r._field == \"% Used\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Networld-%Run",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /:NetWorld-VM-/)\n  |> filter(fn: (r) => r._field == \"% Run\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "NetWorld-%CoStop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /:NetWorld-VM-/)\n  |> filter(fn: (r) => r._field == \"% CoStop\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Networld-% Ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /:NetWorld-VM-/)\n  |> filter(fn: (r) => r._field == \"% Ready\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "pollWorld-% Ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /pollWorld/)\n  |> filter(fn: (r) => r._field == \"% Ready\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "pollWorld-%CoStop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /pollWorld/)\n  |> filter(fn: (r) => r._field == \"% CoStop\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "pollWorld-%Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /pollWorld/)\n  |> filter(fn: (r) => r._field == \"% Used\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "pollWorld-% Run",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /pollWorld/)\n  |> filter(fn: (r) => r._field == \"% Run\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Networld vCPU-PCPU Mapping",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /:NetWorld-VM-/)\n  |> filter(fn: (r) => r._field == \"Physical Cpu\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "vCPU-PCPU-Mapping",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /${Host:regex}/)\n  |> filter(fn: (r) => r.group == \"Vcpu\")\n  |> filter(fn: (r) => r.instance =~ /vmx-vcpu-[0-63]+:UPI_RB_NRDB0/)\t\n  |> filter(fn: (r) => r._field == \"Physical Cpu\")\n  |> group(columns: [\"_measurement\", \"instance\"])\n  |> aggregateWindow(every: 200ms, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}